### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by monolux** [corysimmons/puns#1]
I am having issues with the political correctness of some of these puns.

Do I need to add pun-intended.js in the head to get this to work?

**Comment by corysimmons** [comment]
The PCness of which puns?

**Comment by monolux** [comment]
Now don't get me wrong, I really like them all, my "issue" was meant to be a joke hence the pun-intended.js in the head. I guess you got that fingers crossed.
There are some harsh ones among them though.
The Europe border one is pretty tough considering what is going on.
But hey, got me a few good laughs and a welcome change to the otherwise serious and high attention workflow.
